# Generated by Django 2.2.4 on 2020-04-03 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('token', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('delete_time', models.DateTimeField()),
                ('last_connection', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manager.API')),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.BinaryField()),
                ('salt', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=36)),
                ('done', models.BooleanField(default=False)),
                ('user_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(default=None, max_length=254, unique=True)),
                ('login', models.BooleanField(default=False)),
                ('auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manager.Auth')),
            ],
        ),
        migrations.AddField(
            model_name='auth',
            name='password',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='manager.Password'),
        ),
    ]
