# Generated by Django 2.2.4 on 2020-04-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='api_token',
            field=models.CharField(default=None, max_length=128, unique=True),
        ),
    ]
