# Generated by Django 3.0.5 on 2020-04-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20200404_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='todo_id',
            field=models.BigIntegerField(default=3, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='api',
            name='token',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
