# Generated by Django 3.0.5 on 2020-04-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20200404_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='api_token',
            field=models.CharField(default='None', max_length=64, unique=True),
        ),
    ]
