# Generated by Django 3.0.5 on 2020-04-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20200404_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='api_token',
            field=models.CharField(default='None', max_length=64),
        ),
    ]
