# Generated by Django 3.0.5 on 2020-04-04 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20200404_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='api_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='auth',
            name='password',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='manager.Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, unique=True),
        ),
    ]
