# Generated by Django 3.0.5 on 2020-04-04 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20200404_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='password',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='manager.Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
