# Generated by Django 3.0.5 on 2020-04-04 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20200404_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='api_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='auth',
            name='password',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.Password'),
        ),
    ]
